/**
 * v1.4 Step 2A Curated Knowledge Pack（精选，非全文灌库）。
 *
 * 基于 docs/law 本地选定资料的元数据与精选条款：
 * 01 网络安全法 2025 修正版
 * 02 数据安全法 2021
 * 03 个人信息保护法 2021
 * 04 网络数据安全管理条例 2024
 * 05 GB/T 22239-2019（SUMMARY_ONLY，不入库全文）
 *
 * 映射仅表达控制/义务关联，不得解读为违法结论。
 */
import type { CuratedKnowledgePack } from "./types";

const REVIEWED_AT = "2026-08-09T12:00:00.000Z";
const PUBLISHED_AT = "2026-08-09T12:00:00.000Z";

/** 本地参考 PDF（不提交仓库）sha256，见 docs/law/SOURCES.md */
const SOURCE_FILES = {
  csl: {
    name: "01_中华人民共和国网络安全法_2025修正版.pdf",
    hash: "0e3a212c4414fd097744826d8888068df2ebfd285347d58210e95ab94b37c33d",
  },
  dsl: {
    name: "02_中华人民共和国数据安全法_2021.pdf",
    hash: "44ba4977dbba0e8d8c6c81e352f828e138386ac385c2f73d81233599d7b9a224",
  },
  pipl: {
    name: "03_中华人民共和国个人信息保护法_2021.pdf",
    hash: "4baa3b32f03d5c025548b87a8e224e0a4eeb874ccfc50f6b58e1c5fe9ed3dcb1",
  },
  ndsl: {
    name: "04_网络数据安全管理条例_2024.pdf",
    hash: "7c51c9b66296db6819bb9ab62c3bc7d60946b36fad6e26f06ee181dbc8292df0",
  },
  gbt22239: {
    name: "05_GBT22239-2019_网络安全等级保护基本要求.pdf",
    hash: "254ddd75cac3dec755fd1216f7ef4d3fb8552399b376a1590efd060c537298a4",
  },
} as const;

const ctx = {
  dataCategory: { key: "dataCategory", label: "数据类型/敏感字段" },
  accessedRecordCount: {
    key: "accessedRecordCount",
    label: "访问/返回记录数",
  },
  changeTicketId: { key: "changeTicketId", label: "变更工单编号" },
  businessOwnerConfirmed: {
    key: "businessOwnerConfirmed",
    label: "业务负责人确认结果",
  },
  loginSourceIp: { key: "loginSourceIp", label: "登录来源 IP" },
  destinationRegion: { key: "destinationRegion", label: "数据去向/目的地区域" },
  outboundVolume: { key: "outboundVolume", label: "出站流量规模" },
  occurredAt: { key: "occurredAt", label: "事件发生时间" },
} as const;

const evidence = {
  dbAudit: { key: "db-audit", label: "数据库审计日志（脱敏）" },
  authLog: { key: "auth-log", label: "认证/登录日志（脱敏）" },
  gatewayLog: { key: "gateway-log", label: "出口网关/流量日志（脱敏）" },
  ticket: { key: "change-ticket", label: "变更/运维工单" },
  ownerConfirm: { key: "owner-confirm", label: "业务负责人确认记录" },
  accessPolicy: { key: "access-policy", label: "访问控制策略配置摘录" },
} as const;

const checklist = {
  verifyOwner: { key: "verify-owner", label: "联系业务负责人核实业务合理性" },
  verifyTicket: { key: "verify-ticket", label: "核查是否存在对应变更/计划任务工单" },
  verifyExport: { key: "verify-export", label: "确认数据是否被导出及去向" },
  verifyAccount: { key: "verify-account", label: "核查账号权限与近期认证异常" },
  verifyNetwork: { key: "verify-network", label: "核查异常外联目标与出站流量" },
  escalateIr: { key: "escalate-ir", label: "按事件响应流程升级人工研判" },
} as const;

export const curatedKnowledgePack: CuratedKnowledgePack = {
  packId: "v1.4-curated-cn-core-5",
  packVersion: "2A.0.0",
  reviewedAt: REVIEWED_AT,
  documents: [
    {
      canonicalCode: "CN-CSL",
      title: "中华人民共和国网络安全法",
      documentType: "LAW",
      jurisdiction: "CN",
      issuingAuthority: "全国人民代表大会常务委员会",
      description:
        "网络安全法（含 2025 年修正）。本 pack 仅收录与访问控制、事件响应、用户信息保护相关的精选条款，非全文库。",
      version: {
        versionKey: "2025-amendment",
        versionLabel: "2025年修正版",
        documentNumber: null,
        publishDate: "2025-10-28",
        effectiveDate: "2026-01-01",
        expiryDate: null,
        publicationStatus: "PUBLISHED",
        legalStatus: "EFFECTIVE",
        sourceType: "OFFICIAL_PUBLIC",
        sourceUrl: "https://www.npc.gov.cn/",
        rightsStatus: "PUBLIC",
        contentMode: "FULL_TEXT",
        sourceFileName: SOURCE_FILES.csl.name,
        sourceFileHash: SOURCE_FILES.csl.hash,
        reviewedAt: REVIEWED_AT,
        publishedAt: PUBLISHED_AT,
        clauses: [
          {
            clauseKey: "article-21",
            articleNumber: "第二十一条",
            heading: "网络安全等级保护与安全保护义务",
            originalText:
              "国家实行网络安全等级保护制度。网络运营者应当按照网络安全等级保护制度的要求，履行下列安全保护义务，保障网络免受干扰、破坏或者未经授权的访问，防止网络数据泄露或者被窃取、篡改。",
            summary: "网络运营者须落实等保要求，防止未经授权访问与数据泄露。",
            interpretation:
              "研判场景中可作为访问控制与安全基线核查的义务依据；不得直接据此认定已违法。",
            topics: ["access-control", "baseline", "data-protection"],
            sortOrder: 10,
          },
          {
            clauseKey: "article-25",
            articleNumber: "第二十五条",
            heading: "网络安全事件应急预案",
            originalText:
              "网络运营者应当制定网络安全事件应急预案，及时处置系统漏洞、计算机病毒、网络攻击、网络侵入等安全风险；在发生危害网络安全的事件时，立即启动应急预案，采取相应的补救措施，并按照规定向有关主管部门报告。",
            summary: "要求具备事件应急预案，并在事件发生时处置与报告。",
            interpretation:
              "异常外联、疑似入侵等技术告警可关联事件响应控制；是否构成安全事件须人工确认。",
            topics: ["incident-response", "reporting"],
            sortOrder: 20,
          },
          {
            clauseKey: "article-27",
            articleNumber: "第二十七条",
            heading: "禁止危害网络安全的活动",
            originalText:
              "任何个人和组织不得从事非法侵入他人网络、干扰他人网络正常功能、窃取网络数据等危害网络安全的活动；不得提供专门用于从事侵入网络、干扰网络正常功能及防护措施、窃取网络数据等危害网络安全活动的程序、工具。",
            summary: "禁止非法侵入、干扰与窃取网络数据等危害行为。",
            interpretation:
              "仅在证据充分且经人工研判后可作为升级核查触发；不得自动输出违法结论。",
            topics: ["unauthorized-access", "data-theft", "escalation"],
            sortOrder: 30,
          },
          {
            clauseKey: "article-40",
            articleNumber: "第四十条",
            heading: "用户信息严格保密",
            originalText:
              "网络运营者应当对其收集的用户信息严格保密，并建立健全用户信息保护制度。",
            summary: "对收集的用户信息负有保密与制度建设义务。",
            interpretation:
              "大批量敏感用户数据访问场景可关联隐私/数据保护控制，需结合业务授权上下文。",
            topics: ["privacy", "user-data", "confidentiality"],
            sortOrder: 40,
          },
          {
            clauseKey: "article-21-item-access",
            articleNumber: "第二十一条",
            heading: "防未经授权访问（要点）",
            parentClauseKey: "article-21",
            originalText:
              "采取监测、记录网络运行状态、网络安全事件的技术措施，并按照规定留存相关的网络日志不少于六个月。",
            summary: "强调监测记录与日志留存，支撑事后核查。",
            interpretation: "建议核查是否具备可审计的访问与安全事件日志。",
            topics: ["logging", "audit", "access-control"],
            sortOrder: 11,
          },
        ],
      },
    },
    {
      canonicalCode: "CN-DSL",
      title: "中华人民共和国数据安全法",
      documentType: "LAW",
      jurisdiction: "CN",
      issuingAuthority: "全国人民代表大会常务委员会",
      description:
        "数据安全法（2021）。精选分类分级、风险监测、风险评估与重要数据出境相关条款。",
      version: {
        versionKey: "2021-original",
        versionLabel: "2021年公布施行",
        documentNumber: null,
        publishDate: "2021-06-10",
        effectiveDate: "2021-09-01",
        expiryDate: null,
        publicationStatus: "PUBLISHED",
        legalStatus: "EFFECTIVE",
        sourceType: "OFFICIAL_PUBLIC",
        sourceUrl: "https://www.npc.gov.cn/",
        rightsStatus: "PUBLIC",
        contentMode: "FULL_TEXT",
        sourceFileName: SOURCE_FILES.dsl.name,
        sourceFileHash: SOURCE_FILES.dsl.hash,
        reviewedAt: REVIEWED_AT,
        publishedAt: PUBLISHED_AT,
        clauses: [
          {
            clauseKey: "article-21",
            articleNumber: "第二十一条",
            heading: "数据分类分级保护",
            originalText:
              "国家建立数据分类分级保护制度，根据数据在经济社会发展中的重要程度，以及一旦遭到篡改、破坏、泄露或者非法获取、非法利用，对国家安全、公共利益或者个人、组织合法权益造成的危害程度，对数据实行分类分级保护。",
            summary: "建立并落实数据分类分级保护。",
            interpretation:
              "大批量敏感数据访问研判应先确认数据类别与敏感级别；缺分类信息时标记上下文不足。",
            topics: ["data-classification", "sensitive-data"],
            sortOrder: 10,
          },
          {
            clauseKey: "article-27",
            articleNumber: "第二十七条",
            heading: "数据处理活动风险监测",
            originalText:
              "开展数据处理活动应当依照法律、法规的规定，建立健全全流程数据安全管理制度，组织开展数据安全教育培训，采取相应的技术措施和其他必要措施，保障数据安全。利用互联网等信息网络开展数据处理活动，应当在网络安全等级保护制度的基础上，履行上述数据安全保护义务。",
            summary: "数据处理者须建立全流程安全制度与技术措施。",
            interpretation: "可映射到数据访问控制与基线保护控制项。",
            topics: ["data-protection", "baseline", "access-control"],
            sortOrder: 20,
          },
          {
            clauseKey: "article-29",
            articleNumber: "第二十九条",
            heading: "重要数据风险评估",
            originalText:
              "开展数据处理活动应当加强风险监测，发现数据安全缺陷、漏洞等风险时，应当立即采取补救措施；发生数据安全事件时，应当立即采取处置措施，按照规定及时告知用户并向有关主管部门报告。",
            summary: "强调风险监测、事件处置与报告。",
            interpretation: "异常访问/外联可能触发事件处置核查，不自动等同于已发生泄露。",
            topics: ["incident-response", "risk-monitoring"],
            sortOrder: 30,
          },
          {
            clauseKey: "article-31",
            articleNumber: "第三十一条",
            heading: "重要数据出境安全评估",
            originalText:
              "关键数据处理者向境外提供重要数据，应当按照国家网信部门会同国务院有关部门制定的办法进行安全评估。",
            summary: "关键重要数据出境须按规定安全评估。",
            interpretation:
              "仅当案件出现出境/跨境传输上下文时作为可能义务关联；缺 destinationRegion 不得推定出境。",
            topics: ["cross-border", "important-data"],
            sortOrder: 40,
          },
          {
            clauseKey: "article-32",
            articleNumber: "第三十二条",
            heading: "依法留存与提供数据",
            originalText:
              "任何组织、个人收集数据，必须采取合法、正当的方式，不得窃取或者以其他非法方式获取数据。",
            summary: "禁止以窃取或其他非法方式获取数据。",
            interpretation: "可作为未授权批量获取场景的升级核查触发，须证据与人工确认。",
            topics: ["unauthorized-access", "escalation"],
            sortOrder: 50,
          },
        ],
      },
    },
    {
      canonicalCode: "CN-PIPL",
      title: "中华人民共和国个人信息保护法",
      documentType: "LAW",
      jurisdiction: "CN",
      issuingAuthority: "全国人民代表大会常务委员会",
      description:
        "个人信息保护法（2021）。精选处理合法性、安全措施与泄露通知相关条款。",
      version: {
        versionKey: "2021-original",
        versionLabel: "2021年公布施行",
        documentNumber: null,
        publishDate: "2021-08-20",
        effectiveDate: "2021-11-01",
        expiryDate: null,
        publicationStatus: "PUBLISHED",
        legalStatus: "EFFECTIVE",
        sourceType: "OFFICIAL_PUBLIC",
        sourceUrl: "https://www.npc.gov.cn/",
        rightsStatus: "PUBLIC",
        contentMode: "FULL_TEXT",
        sourceFileName: SOURCE_FILES.pipl.name,
        sourceFileHash: SOURCE_FILES.pipl.hash,
        reviewedAt: REVIEWED_AT,
        publishedAt: PUBLISHED_AT,
        clauses: [
          {
            clauseKey: "article-13",
            articleNumber: "第十三条",
            heading: "处理个人信息的合法性基础",
            originalText:
              "符合下列情形之一的，个人信息处理者方可处理个人信息：（一）取得个人的同意；（二）为订立、履行个人作为一方当事人的合同所必需……法律、行政法规规定的其他情形。",
            summary: "处理个人信息须具备法定合法性基础。",
            interpretation:
              "业务合理性确认可降低运营关注，但不自动证明合法性基础已满足；系统不输出合法/违法结论。",
            topics: ["privacy", "lawful-basis", "business-context"],
            sortOrder: 10,
          },
          {
            clauseKey: "article-51",
            articleNumber: "第五十一条",
            heading: "个人信息安全技术与管理措施",
            originalText:
              "个人信息处理者应当根据个人信息的处理目的、处理方式、个人信息的种类以及对个人权益的影响、可能存在的安全风险等，采取下列措施确保个人信息处理活动符合法律、行政法规的规定，并防止未经授权的访问以及个人信息泄露、篡改、丢失。",
            summary: "要求采取必要措施防止未经授权访问与泄露。",
            interpretation: "映射敏感个人信息访问控制与审计要求。",
            topics: ["access-control", "privacy", "security-measures"],
            sortOrder: 20,
          },
          {
            clauseKey: "article-51-access",
            articleNumber: "第五十一条",
            heading: "访问控制与审计（要点）",
            parentClauseKey: "article-51",
            originalText:
              "（二）对个人信息处理进行合规审计，并对处理情况进行记录；（四）采取相应的加密、去标识化等安全技术措施；（五）合理确定个人信息处理的操作权限，并定期进行安全教育和培训。",
            summary: "强调权限最小化、审计与加密/去标识化。",
            interpretation: "批量访问与权限异常场景应核查操作权限与审计记录。",
            topics: ["least-privilege", "audit", "encryption"],
            sortOrder: 21,
          },
          {
            clauseKey: "article-57",
            articleNumber: "第五十七条",
            heading: "个人信息泄露等通知义务",
            originalText:
              "发生或者可能发生个人信息泄露、篡改、丢失的，个人信息处理者应当立即采取补救措施，并通知履行个人信息保护职责的部门和个人。",
            summary: "发生或可能发生泄露等情形时应补救并通知。",
            interpretation:
              "仅作事件升级/核查触发；“可能发生”不等于已确认泄露。",
            topics: ["incident-response", "breach-notification", "escalation"],
            sortOrder: 30,
          },
          {
            clauseKey: "article-21",
            articleNumber: "第二十一条",
            heading: "委托处理",
            originalText:
              "个人信息处理者委托处理个人信息的，应当与受托人约定委托处理的目的、期限、处理方式、个人信息的种类、保护措施以及双方的权利和义务等，并对受托人的个人信息处理活动进行监督。",
            summary: "委托处理须约定目的、范围与保护措施并监督。",
            interpretation: "涉及第三方/运维账号访问时核查委托与授权边界。",
            topics: ["entrusted-processing", "third-party"],
            sortOrder: 40,
          },
        ],
      },
    },
    {
      canonicalCode: "CN-NDSL-REGULATION",
      title: "网络数据安全管理条例",
      documentType: "REGULATION",
      jurisdiction: "CN",
      issuingAuthority: "国务院",
      description:
        "网络数据安全管理条例（2024 公布）。精选网络数据处理者安全保护、重要数据与安全事件相关要点。",
      version: {
        versionKey: "2024-original",
        versionLabel: "2024年公布（2025年施行）",
        documentNumber: null,
        publishDate: "2024-09-30",
        effectiveDate: "2025-01-01",
        expiryDate: null,
        publicationStatus: "PUBLISHED",
        legalStatus: "EFFECTIVE",
        sourceType: "OFFICIAL_PUBLIC",
        sourceUrl: "https://www.gov.cn/",
        rightsStatus: "PUBLIC",
        contentMode: "FULL_TEXT",
        sourceFileName: SOURCE_FILES.ndsl.name,
        sourceFileHash: SOURCE_FILES.ndsl.hash,
        reviewedAt: REVIEWED_AT,
        publishedAt: PUBLISHED_AT,
        clauses: [
          {
            clauseKey: "article-9",
            articleNumber: "第九条",
            heading: "网络数据安全保护义务",
            originalText:
              "网络数据处理者应当建立健全网络数据安全管理制度，采取技术措施和其他必要措施保障网络数据安全，加强风险监测，不得危害国家安全、公共利益，不得损害个人、组织的合法权益。",
            summary: "网络数据处理者须建立制度并采取必要安全措施。",
            interpretation: "覆盖数据与网络安全联合研判的通用控制支撑。",
            topics: ["data-protection", "risk-monitoring"],
            sortOrder: 10,
          },
          {
            clauseKey: "article-11",
            articleNumber: "第十一条",
            heading: "身份认证与权限管理",
            originalText:
              "网络数据处理者应当采取身份鉴别、访问控制等技术措施，防止网络数据被窃取或者篡改；对重要数据进行处理的，还应当对数据分类、权限管理、访问日志等提出更高要求。",
            summary: "强调身份鉴别、访问控制与重要数据更高要求。",
            interpretation: "直接支撑身份异常与敏感数据访问控制映射。",
            topics: ["identity", "access-control", "important-data"],
            sortOrder: 20,
          },
          {
            clauseKey: "article-27",
            articleNumber: "第二十七条",
            heading: "重要数据识别与保护",
            originalText:
              "国家建立重要数据目录管理制度。网络数据处理者应当按照相关规定识别、申报重要数据，并对重要数据采取加强保护措施。",
            summary: "重要数据需识别、申报并加强保护。",
            interpretation: "缺数据类别/是否重要数据时应提示补充上下文。",
            topics: ["important-data", "data-classification"],
            sortOrder: 30,
          },
          {
            clauseKey: "article-33",
            articleNumber: "第三十三条",
            heading: "网络数据安全事件处置",
            originalText:
              "发生网络数据安全事件，网络数据处理者应当立即启动应急响应，采取补救措施，按规定向有关主管部门报告，并告知可能受到影响的个人、组织。",
            summary: "安全事件须应急响应、报告并告知受影响方。",
            interpretation: "异常外联/批量访问升级场景的事件响应触发依据。",
            topics: ["incident-response", "escalation"],
            sortOrder: 40,
          },
          {
            clauseKey: "article-36",
            articleNumber: "第三十六条",
            heading: "出境与跨境传输相关要求（要点）",
            originalText:
              "网络数据处理者向境外提供个人信息、重要数据的，应当依法通过安全评估、个人信息保护认证或按照标准合同等国家规定条件进行。",
            summary: "向境外提供个人信息/重要数据须符合法定条件。",
            interpretation:
              "仅当存在出境迹象时作为可能义务；缺目的地信息不得推定。",
            topics: ["cross-border", "privacy", "important-data"],
            sortOrder: 50,
          },
        ],
      },
    },
    {
      canonicalCode: "CN-GBT-22239",
      title: "信息安全技术 网络安全等级保护基本要求（GB/T 22239-2019）",
      documentType: "STANDARD",
      jurisdiction: "CN",
      issuingAuthority: "国家市场监督管理总局 / 国家标准化管理委员会",
      description:
        "等保基本要求（2019）。第一版仅收录 SUMMARY_ONLY 精选要求要点，不灌标准全文；详情见官方渠道。",
      version: {
        versionKey: "2019",
        versionLabel: "GB/T 22239-2019",
        documentNumber: "GB/T 22239-2019",
        publishDate: "2019-05-10",
        effectiveDate: "2019-12-01",
        expiryDate: null,
        publicationStatus: "PUBLISHED",
        legalStatus: "EFFECTIVE",
        sourceType: "OFFICIAL_PUBLIC",
        sourceUrl: "https://openstd.samr.gov.cn/",
        rightsStatus: "UNKNOWN",
        contentMode: "SUMMARY_ONLY",
        sourceFileName: SOURCE_FILES.gbt22239.name,
        sourceFileHash: SOURCE_FILES.gbt22239.hash,
        reviewedAt: REVIEWED_AT,
        publishedAt: PUBLISHED_AT,
        clauses: [
          {
            clauseKey: "req-identity-auth",
            articleNumber: null,
            section: "安全计算环境",
            heading: "身份鉴别（精选要求）",
            originalText: null,
            summary:
              "应对登录用户进行身份标识和鉴别；口令、密码技术、生物技术等；限制非法登录尝试并配置相关审计。",
            interpretation:
              "支撑非常用来源 IP、连续认证失败等身份类规则的控制核查建议。标准全文不入库。",
            topics: ["identity", "authentication"],
            sortOrder: 10,
          },
          {
            clauseKey: "req-access-control",
            articleNumber: null,
            section: "安全计算环境",
            heading: "访问控制（精选要求）",
            originalText: null,
            summary:
              "应启用访问控制功能，依据安全策略控制用户对客体的访问；权限最小化；分离特权用户与普通用户。",
            interpretation: "映射敏感数据访问与多系统访问场景的权限最小化核查。",
            topics: ["access-control", "least-privilege"],
            sortOrder: 20,
          },
          {
            clauseKey: "req-security-audit",
            articleNumber: null,
            section: "安全计算环境",
            heading: "安全审计（精选要求）",
            originalText: null,
            summary:
              "应启用安全审计，覆盖用户行为与重要安全事件；审计记录保护防删除/篡改；支持审计查阅与分析。",
            interpretation: "批量访问、认证异常均依赖可审计日志；缺日志则上下文不足。",
            topics: ["audit", "logging"],
            sortOrder: 30,
          },
          {
            clauseKey: "req-boundary",
            articleNumber: null,
            section: "安全区域边界",
            heading: "边界防护与访问控制（精选要求）",
            originalText: null,
            summary:
              "应保证跨越边界的访问和数据流通过受控接口；对进出网络的数据流进行安全检测与访问控制。",
            interpretation: "支撑异常公网通信/出站流量类规则的网络控制映射。",
            topics: ["network-boundary", "egress"],
            sortOrder: 40,
          },
          {
            clauseKey: "req-incident",
            articleNumber: null,
            section: "安全管理中心 / 应急",
            heading: "安全事件处置（精选要求）",
            originalText: null,
            summary:
              "应制定安全事件报告和处置管理制度，明确事件分级、报告流程与处置职责，并定期演练。",
            interpretation: "技术异常升级人工/流程核查时的制度控制参考。",
            topics: ["incident-response", "governance"],
            sortOrder: 50,
          },
          {
            clauseKey: "req-data-integrity",
            articleNumber: null,
            section: "安全计算环境",
            heading: "数据完整性与保密性（精选要求）",
            originalText: null,
            summary:
              "应采用校验或密码技术保证重要数据完整性；对敏感信息采取加密等保密措施。",
            interpretation: "与敏感数据访问、防泄露技术措施相关，不作合规符合性判定。",
            topics: ["data-protection", "encryption"],
            sortOrder: 60,
          },
        ],
      },
    },
  ],
  controls: [
    {
      controlCode: "CTRL-DATA-ACCESS-01",
      title: "敏感数据访问控制与审计",
      domain: "DATA",
      description:
        "对敏感/重要数据的访问实施权限控制、量级异常监测与可审计记录。",
      objectives: "发现并核查大批量或异常敏感数据访问是否具备授权与业务合理性。",
      requiredContext: [ctx.dataCategory, ctx.accessedRecordCount],
      suggestedEvidence: [evidence.dbAudit, evidence.accessPolicy],
      suggestedChecklistItems: [
        checklist.verifyOwner,
        checklist.verifyTicket,
        checklist.verifyExport,
      ],
      status: "ACTIVE",
    },
    {
      controlCode: "CTRL-DATA-CLASSIFY-01",
      title: "数据分类分级识别",
      domain: "DATA",
      description: "识别数据类别与敏感级别，作为访问与出境类义务关联前提。",
      objectives: "避免在未知数据类别时作出过强义务关联。",
      requiredContext: [ctx.dataCategory],
      suggestedEvidence: [evidence.dbAudit],
      suggestedChecklistItems: [checklist.verifyOwner],
      status: "ACTIVE",
    },
    {
      controlCode: "CTRL-DATA-EXPORT-01",
      title: "数据导出与出境核查",
      domain: "DATA",
      description: "核查数据是否导出/跨境及是否具备相应评估或授权上下文。",
      objectives: "在出现出境迹象时提示可能义务，而非认定违法。",
      requiredContext: [ctx.destinationRegion, ctx.dataCategory],
      suggestedEvidence: [evidence.dbAudit, evidence.gatewayLog],
      suggestedChecklistItems: [checklist.verifyExport],
      status: "ACTIVE",
    },
    {
      controlCode: "CTRL-IAM-AUTH-01",
      title: "身份鉴别与异常登录核查",
      domain: "IDENTITY",
      description: "对异常来源、失败后成功等登录行为进行身份鉴别有效性核查。",
      objectives: "确认账号使用是否符合策略与本人/授权使用。",
      requiredContext: [ctx.loginSourceIp, ctx.occurredAt],
      suggestedEvidence: [evidence.authLog],
      suggestedChecklistItems: [checklist.verifyAccount],
      status: "ACTIVE",
    },
    {
      controlCode: "CTRL-IAM-PRIV-01",
      title: "权限最小化与多系统访问",
      domain: "IDENTITY",
      description: "核查短时间跨系统访问是否符合岗位权限与授权范围。",
      objectives: "识别权限过大或异常横向访问迹象，供人工确认。",
      requiredContext: [ctx.occurredAt],
      suggestedEvidence: [evidence.authLog, evidence.accessPolicy],
      suggestedChecklistItems: [checklist.verifyAccount, checklist.verifyOwner],
      status: "ACTIVE",
    },
    {
      controlCode: "CTRL-NETWORK-BOUNDARY-01",
      title: "网络边界与出站控制",
      domain: "NETWORK",
      description: "对异常公网通信与出站流量实施边界检测与核查。",
      objectives: "确认外联目标/流量是否符合业务与安全策略。",
      requiredContext: [ctx.outboundVolume, ctx.destinationRegion],
      suggestedEvidence: [evidence.gatewayLog],
      suggestedChecklistItems: [checklist.verifyNetwork],
      status: "ACTIVE",
    },
    {
      controlCode: "CTRL-INCIDENT-01",
      title: "安全事件响应与升级",
      domain: "INCIDENT_RESPONSE",
      description: "在达到阈值或出现危害迹象时启动应急与上报核查流程。",
      objectives: "提供升级触发，不自动宣布安全事件或违法。",
      requiredContext: [ctx.occurredAt],
      suggestedEvidence: [evidence.gatewayLog, evidence.dbAudit],
      suggestedChecklistItems: [checklist.escalateIr, checklist.verifyOwner],
      status: "ACTIVE",
    },
    {
      controlCode: "CTRL-PRIVACY-01",
      title: "个人信息保护措施",
      domain: "PRIVACY",
      description: "围绕个人信息访问、委托处理与泄露通知的保护措施核查。",
      objectives: "关联隐私义务要点，保持证据优先与人工确认。",
      requiredContext: [ctx.dataCategory],
      suggestedEvidence: [evidence.dbAudit, evidence.accessPolicy],
      suggestedChecklistItems: [checklist.verifyOwner, checklist.verifyExport],
      status: "ACTIVE",
    },
    {
      controlCode: "CTRL-BUSINESS-AUTH-01",
      title: "业务授权与变更合理性",
      domain: "BUSINESS",
      description: "通过工单、负责人确认与业务说明判断技术异常是否可能为授权行为。",
      objectives: "技术异常 + 业务确认合法 → 可降为正常授权业务行为（人工确认）。",
      requiredContext: [ctx.changeTicketId, ctx.businessOwnerConfirmed],
      suggestedEvidence: [evidence.ticket, evidence.ownerConfirm],
      suggestedChecklistItems: [checklist.verifyTicket, checklist.verifyOwner],
      status: "ACTIVE",
    },
    {
      controlCode: "CTRL-GOVERNANCE-01",
      title: "安全制度与基线治理",
      domain: "GOVERNANCE",
      description: "等保/制度类基线要求的治理控制词汇（摘要级）。",
      objectives: "为基线类核查提供控制锚点，不作测评符合性结论。",
      requiredContext: [],
      suggestedEvidence: [evidence.accessPolicy],
      suggestedChecklistItems: [checklist.verifyOwner],
      status: "ACTIVE",
    },
  ],
  ruleControlMappings: [
    {
      ruleId: "DATA-001",
      controlCode: "CTRL-DATA-ACCESS-01",
      relation: "PRIMARY",
      rationale: "大批量敏感数据访问直接关联访问控制与审计控制。",
      priority: 10,
    },
    {
      ruleId: "DATA-001",
      controlCode: "CTRL-PRIVACY-01",
      relation: "SUPPORTING",
      rationale: "涉及敏感个人信息时补充隐私保护措施核查。",
      priority: 20,
    },
    {
      ruleId: "DATA-002",
      controlCode: "CTRL-DATA-ACCESS-01",
      relation: "PRIMARY",
      rationale: "偏离历史基线的访问仍属敏感数据访问监测范畴。",
      priority: 10,
    },
    {
      ruleId: "DATA-002",
      controlCode: "CTRL-DATA-CLASSIFY-01",
      relation: "SUPPORTING",
      rationale: "基线异常解读依赖数据类别上下文。",
      priority: 20,
    },
    {
      ruleId: "DATA-003",
      controlCode: "CTRL-DATA-ACCESS-01",
      relation: "PRIMARY",
      rationale: "非工作时间敏感访问属于访问控制异常核查。",
      priority: 10,
    },
    {
      ruleId: "DATA-003",
      controlCode: "CTRL-BUSINESS-AUTH-01",
      relation: "SUPPORTING",
      rationale: "需结合计划任务/工单判断是否授权运维窗口。",
      priority: 20,
    },
    {
      ruleId: "IDENTITY-001",
      controlCode: "CTRL-IAM-AUTH-01",
      relation: "PRIMARY",
      rationale: "非常用来源 IP 直接关联身份鉴别控制。",
      priority: 10,
    },
    {
      ruleId: "IDENTITY-002",
      controlCode: "CTRL-IAM-AUTH-01",
      relation: "PRIMARY",
      rationale: "连续失败后成功登录关联异常登录核查。",
      priority: 10,
    },
    {
      ruleId: "IDENTITY-003",
      controlCode: "CTRL-IAM-PRIV-01",
      relation: "PRIMARY",
      rationale: "短时间多系统访问关联权限最小化核查。",
      priority: 10,
    },
    {
      ruleId: "NETWORK-001",
      controlCode: "CTRL-NETWORK-BOUNDARY-01",
      relation: "PRIMARY",
      rationale: "异常公网通信关联边界与出站控制。",
      priority: 10,
    },
    {
      ruleId: "NETWORK-001",
      controlCode: "CTRL-INCIDENT-01",
      relation: "SUPPORTING",
      rationale: "达到危害迹象阈值时可升级事件响应核查。",
      priority: 20,
    },
    {
      ruleId: "NETWORK-002",
      controlCode: "CTRL-NETWORK-BOUNDARY-01",
      relation: "PRIMARY",
      rationale: "异常出站流量关联边界控制。",
      priority: 10,
    },
    {
      ruleId: "NETWORK-002",
      controlCode: "CTRL-DATA-EXPORT-01",
      relation: "SUPPORTING",
      rationale: "出站异常可能伴随数据外传，需核查去向上下文。",
      priority: 20,
    },
    {
      ruleId: "BUSINESS-001",
      controlCode: "CTRL-BUSINESS-AUTH-01",
      relation: "PRIMARY",
      rationale: "变更工单核查是业务授权控制的核心。",
      priority: 10,
    },
    {
      ruleId: "BUSINESS-002",
      controlCode: "CTRL-BUSINESS-AUTH-01",
      relation: "PRIMARY",
      rationale: "业务负责人确认直接支撑业务合理性判断。",
      priority: 10,
    },
    {
      ruleId: "BUSINESS-003",
      controlCode: "CTRL-BUSINESS-AUTH-01",
      relation: "PRIMARY",
      rationale: "业务合理性综合判断依赖授权上下文。",
      priority: 10,
    },
    {
      ruleId: "BUSINESS-003",
      controlCode: "CTRL-INCIDENT-01",
      relation: "SUPPORTING",
      rationale: "业务无法合理解释且技术风险高时可升级事件响应。",
      priority: 30,
    },
  ],
  controlClauseMappings: [
    // DATA access
    {
      controlCode: "CTRL-DATA-ACCESS-01",
      documentCanonicalCode: "CN-DSL",
      versionKey: "2021-original",
      clauseKey: "article-27",
      relationType: "CONTROL_SUPPORT",
      rationale: "数据处理活动安全制度与技术措施支撑访问控制核查。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-DATA-ACCESS-01",
      documentCanonicalCode: "CN-PIPL",
      versionKey: "2021-original",
      clauseKey: "article-51",
      relationType: "CONTROL_SUPPORT",
      rationale: "个人信息安全措施要求防止未经授权访问。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-DATA-ACCESS-01",
      documentCanonicalCode: "CN-NDSL-REGULATION",
      versionKey: "2024-original",
      clauseKey: "article-11",
      relationType: "CONTROL_SUPPORT",
      rationale: "条例明确身份鉴别与访问控制技术措施。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-DATA-ACCESS-01",
      documentCanonicalCode: "CN-GBT-22239",
      versionKey: "2019",
      clauseKey: "req-access-control",
      relationType: "CONTROL_SUPPORT",
      rationale: "等保访问控制精选要求（摘要）支撑技术核查项。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    // classify
    {
      controlCode: "CTRL-DATA-CLASSIFY-01",
      documentCanonicalCode: "CN-DSL",
      versionKey: "2021-original",
      clauseKey: "article-21",
      relationType: "CONTROL_SUPPORT",
      rationale: "分类分级制度是敏感数据识别前提。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-DATA-CLASSIFY-01",
      documentCanonicalCode: "CN-NDSL-REGULATION",
      versionKey: "2024-original",
      clauseKey: "article-27",
      relationType: "POSSIBLE_OBLIGATION",
      rationale: "重要数据识别在补齐数据类别后可能相关。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    // export
    {
      controlCode: "CTRL-DATA-EXPORT-01",
      documentCanonicalCode: "CN-DSL",
      versionKey: "2021-original",
      clauseKey: "article-31",
      relationType: "POSSIBLE_OBLIGATION",
      rationale: "出现重要数据出境迹象时可能涉及安全评估义务。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
      requiredContext: [ctx.destinationRegion, ctx.dataCategory],
    },
    {
      controlCode: "CTRL-DATA-EXPORT-01",
      documentCanonicalCode: "CN-NDSL-REGULATION",
      versionKey: "2024-original",
      clauseKey: "article-36",
      relationType: "POSSIBLE_OBLIGATION",
      rationale: "向境外提供个人信息/重要数据时的可能条件关联。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
      requiredContext: [ctx.destinationRegion],
    },
    // IAM
    {
      controlCode: "CTRL-IAM-AUTH-01",
      documentCanonicalCode: "CN-NDSL-REGULATION",
      versionKey: "2024-original",
      clauseKey: "article-11",
      relationType: "CONTROL_SUPPORT",
      rationale: "身份鉴别要求支撑异常登录核查。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-IAM-AUTH-01",
      documentCanonicalCode: "CN-GBT-22239",
      versionKey: "2019",
      clauseKey: "req-identity-auth",
      relationType: "CONTROL_SUPPORT",
      rationale: "等保身份鉴别精选要求（摘要）。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-IAM-PRIV-01",
      documentCanonicalCode: "CN-PIPL",
      versionKey: "2021-original",
      clauseKey: "article-51-access",
      relationType: "CONTROL_SUPPORT",
      rationale: "操作权限合理化支撑多系统访问核查。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-IAM-PRIV-01",
      documentCanonicalCode: "CN-GBT-22239",
      versionKey: "2019",
      clauseKey: "req-access-control",
      relationType: "CONTROL_SUPPORT",
      rationale: "等保访问控制/权限最小化精选要求。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    // network
    {
      controlCode: "CTRL-NETWORK-BOUNDARY-01",
      documentCanonicalCode: "CN-CSL",
      versionKey: "2025-amendment",
      clauseKey: "article-21",
      relationType: "CONTROL_SUPPORT",
      rationale: "安全保护义务包含防干扰与未经授权访问。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-NETWORK-BOUNDARY-01",
      documentCanonicalCode: "CN-GBT-22239",
      versionKey: "2019",
      clauseKey: "req-boundary",
      relationType: "CONTROL_SUPPORT",
      rationale: "等保边界防护精选要求（摘要）。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    // incident
    {
      controlCode: "CTRL-INCIDENT-01",
      documentCanonicalCode: "CN-CSL",
      versionKey: "2025-amendment",
      clauseKey: "article-25",
      relationType: "CONTROL_SUPPORT",
      rationale: "应急预案与事件处置义务支撑响应控制。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-INCIDENT-01",
      documentCanonicalCode: "CN-CSL",
      versionKey: "2025-amendment",
      clauseKey: "article-27",
      relationType: "ESCALATION_TRIGGER",
      rationale: "出现危害网络安全活动迹象时应升级人工核查（非自动违法认定）。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-INCIDENT-01",
      documentCanonicalCode: "CN-PIPL",
      versionKey: "2021-original",
      clauseKey: "article-57",
      relationType: "ESCALATION_TRIGGER",
      rationale: "可能发生个人信息泄露等情形时的通知/补救升级触发。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-INCIDENT-01",
      documentCanonicalCode: "CN-NDSL-REGULATION",
      versionKey: "2024-original",
      clauseKey: "article-33",
      relationType: "ESCALATION_TRIGGER",
      rationale: "网络数据安全事件处置与报告升级触发。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-INCIDENT-01",
      documentCanonicalCode: "CN-GBT-22239",
      versionKey: "2019",
      clauseKey: "req-incident",
      relationType: "CONTROL_SUPPORT",
      rationale: "等保安全事件处置制度精选要求（摘要）。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    // privacy
    {
      controlCode: "CTRL-PRIVACY-01",
      documentCanonicalCode: "CN-PIPL",
      versionKey: "2021-original",
      clauseKey: "article-13",
      relationType: "POSSIBLE_OBLIGATION",
      rationale: "处理个人信息合法性基础在补齐业务/同意等上下文后可能相关。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-PRIVACY-01",
      documentCanonicalCode: "CN-CSL",
      versionKey: "2025-amendment",
      clauseKey: "article-40",
      relationType: "CONTROL_SUPPORT",
      rationale: "用户信息保密义务支撑隐私保护控制。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-PRIVACY-01",
      documentCanonicalCode: "CN-PIPL",
      versionKey: "2021-original",
      clauseKey: "article-21",
      relationType: "POSSIBLE_OBLIGATION",
      rationale: "涉及委托/第三方处理时可能相关。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    // business
    {
      controlCode: "CTRL-BUSINESS-AUTH-01",
      documentCanonicalCode: "CN-PIPL",
      versionKey: "2021-original",
      clauseKey: "article-13",
      relationType: "CONTROL_SUPPORT",
      rationale: "业务授权上下文有助于理解处理活动是否具备业务必要性线索（非法律结论）。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-BUSINESS-AUTH-01",
      documentCanonicalCode: "CN-DSL",
      versionKey: "2021-original",
      clauseKey: "article-27",
      relationType: "CONTROL_SUPPORT",
      rationale: "全流程管理制度核查可与变更/授权流程交叉验证。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    // governance / baseline
    {
      controlCode: "CTRL-GOVERNANCE-01",
      documentCanonicalCode: "CN-CSL",
      versionKey: "2025-amendment",
      clauseKey: "article-21",
      relationType: "CONTROL_SUPPORT",
      rationale: "等保制度法律要求与治理基线控制对应。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-GOVERNANCE-01",
      documentCanonicalCode: "CN-GBT-22239",
      versionKey: "2019",
      clauseKey: "req-security-audit",
      relationType: "CONTROL_SUPPORT",
      rationale: "安全审计基线精选要求（摘要）。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-GOVERNANCE-01",
      documentCanonicalCode: "CN-GBT-22239",
      versionKey: "2019",
      clauseKey: "req-data-integrity",
      relationType: "CONTROL_SUPPORT",
      rationale: "数据完整性/保密性精选要求（摘要）。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-DATA-ACCESS-01",
      documentCanonicalCode: "CN-CSL",
      versionKey: "2025-amendment",
      clauseKey: "article-21-item-access",
      relationType: "CONTROL_SUPPORT",
      rationale: "日志监测与留存支撑访问审计。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-DATA-ACCESS-01",
      documentCanonicalCode: "CN-GBT-22239",
      versionKey: "2019",
      clauseKey: "req-security-audit",
      relationType: "CONTROL_SUPPORT",
      rationale: "安全审计精选要求支撑访问行为核查。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-INCIDENT-01",
      documentCanonicalCode: "CN-DSL",
      versionKey: "2021-original",
      clauseKey: "article-29",
      relationType: "ESCALATION_TRIGGER",
      rationale: "数据安全事件处置与报告要求作为升级触发。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
    {
      controlCode: "CTRL-DATA-EXPORT-01",
      documentCanonicalCode: "CN-DSL",
      versionKey: "2021-original",
      clauseKey: "article-32",
      relationType: "ESCALATION_TRIGGER",
      rationale: "疑似以非法方式获取数据时升级人工核查（非自动违法结论）。",
      reviewStatus: "APPROVED",
      reviewedAt: REVIEWED_AT,
    },
  ],
};

export function countPackEntities(pack: CuratedKnowledgePack = curatedKnowledgePack) {
  const clauses = pack.documents.reduce(
    (n, d) => n + d.version.clauses.length,
    0,
  );
  return {
    documents: pack.documents.length,
    versions: pack.documents.length,
    clauses,
    controls: pack.controls.length,
    ruleControlMappings: pack.ruleControlMappings.length,
    controlClauseMappings: pack.controlClauseMappings.length,
  };
}
