"use client";

import { useState } from "react";
import type { TimelineEvent } from "@/domain/types";
import { formatDateTimeForDisplay } from "@/lib/formatDateTimeForDisplay";
import { Panel } from "./common";

const eventTypeOptions = ["认证", "数据访问", "网络通信", "系统访问", "告警", "其他"] as const;
let humanEventSequence = 0;

export function TimelinePanel({ events, onAdd, canAdd = true, onEntityClick, onEvidenceClick }: { events: TimelineEvent[]; onAdd: (event: TimelineEvent) => void; canAdd?: boolean; onEntityClick?: (kind: string, value: string) => void; onEvidenceClick?: (id: string) => void }) {
  const [time, setTime] = useState("");
  const [operator, setOperator] = useState("");
  const [eventType, setEventType] = useState<string>("其他");
  const [description, setDescription] = useState("");
  const [showAddForm, setShowAddForm] = useState(false);
  const sorted = [...events].sort((a, b) => a.occurredAt.localeCompare(b.occurredAt));
  const handleAdd = () => { if (!canAdd || !time || !description.trim()) return; humanEventSequence += 1; onAdd({ id: `human-tl-${humanEventSequence}`, occurredAt: new Date(time).toISOString(), eventType, title: description.trim().slice(0, 20), description: description.trim(), operator: operator.trim() || null, source: "HUMAN" }); setTime(""); setOperator(""); setDescription(""); setShowAddForm(false); };
  return <Panel title={`事件时间线（${sorted.length} 条）`}>
    {sorted.length === 0 ? <p className="text-sm text-neutral-500">{canAdd ? "暂无时间线记录，可补充案件实际发生的事件事实。" : "暂无时间线记录。"}</p> : null}
    <ol className="relative space-y-3 border-l border-neutral-200 pl-4">{sorted.map((event) => <li key={event.id} className="relative"><span className={`absolute -left-[21px] top-1.5 h-2.5 w-2.5 rounded-full ${event.source === "HUMAN" ? "bg-blue-500" : "bg-neutral-400"}`} /><div className="flex flex-wrap items-center gap-2 text-xs text-neutral-500"><span className="font-mono">{formatDateTimeForDisplay(event.occurredAt)}</span><span className="rounded bg-neutral-100 px-1.5 py-0.5">{event.eventType}</span>{event.source === "HUMAN" ? <span className="rounded bg-blue-50 px-1.5 py-0.5 text-blue-700">人工补充{event.operator ? ` · ${event.operator}` : ""}</span> : null}</div><div className="mt-0.5 break-words text-sm font-medium text-[var(--ui-text-primary)]">{event.title}</div><p className="break-words text-xs leading-5 text-[var(--ui-text-secondary)]">{event.description}</p>{event.relatedEntityRefs?.length ? <div className="mt-1 flex flex-wrap gap-1.5">{event.relatedEntityRefs.map((ref) => <button key={`${ref.kind}:${ref.value}`} type="button" className="rounded border border-blue-200 px-1.5 py-0.5 text-xs text-blue-700 hover:bg-blue-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--ui-focus-ring)]" onClick={() => onEntityClick?.(ref.kind, ref.value)}>{ref.kind} · {ref.value}</button>)}</div> : null}{event.evidenceIds?.length ? <div className="mt-1 flex flex-wrap gap-1.5">{event.evidenceIds.map((id) => <button key={id} type="button" className="rounded border border-slate-200 px-1.5 py-0.5 text-xs text-slate-700 hover:bg-slate-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--ui-focus-ring)]" onClick={() => onEvidenceClick?.(id)}>证据 {id} →</button>)}</div> : null}</li>)}</ol>
    {canAdd ? <div className="mt-4 border-t border-neutral-100 pt-3"><button type="button" className="text-xs font-medium text-[var(--ui-brand-hover)] underline underline-offset-2 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--ui-focus-ring)]" aria-expanded={showAddForm} onClick={() => setShowAddForm((value) => !value)}>{showAddForm ? "收起补充事件" : "+ 补充事件时间线"}</button>{showAddForm ? <div className="mt-2 space-y-2" data-testid="timeline-add-form"><p className="text-xs leading-5 text-neutral-500">用于补充案件实际发生的事件事实，不用于记录研判人员操作。</p><div className="flex flex-wrap gap-2"><input aria-label="事件时间" type="datetime-local" className="rounded border border-neutral-300 px-2 py-1 text-sm" value={time} onChange={(e) => setTime(e.target.value)} /><input aria-label="录入人" className="w-32 rounded border border-neutral-300 px-2 py-1 text-sm" value={operator} placeholder="录入人" onChange={(e) => setOperator(e.target.value)} /><select aria-label="事件类型" className="rounded border border-neutral-300 px-2 py-1 text-sm" value={eventType} onChange={(e) => setEventType(e.target.value)}>{eventTypeOptions.map((option) => <option key={option} value={option}>{option}</option>)}</select></div><div className="flex gap-2"><input aria-label="事件事实说明" className="min-w-0 flex-1 rounded border border-neutral-300 px-2 py-1 text-sm" value={description} placeholder="事件事实说明…" onChange={(e) => setDescription(e.target.value)} /><button type="button" className="rounded bg-neutral-800 px-3 py-1 text-sm text-white hover:bg-neutral-700 disabled:opacity-40 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--ui-focus-ring)]" disabled={!time || !description.trim()} onClick={handleAdd}>添加</button></div></div> : null}</div> : null}
  </Panel>;
}
